name: Build autotracker

on:
  push:
    tags:
      - autotracker-*

jobs:
  parse-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      upload-url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - id: get-version
        run: tag=`git describe --exact-match --tags`; echo "version=${tag/autotracker-/}" >> "$GITHUB_OUTPUT"
      - uses: ncipollo/release-action@v1
        id: create-release
        with:
          draft: true

  build-autotracker-linux:
    runs-on: ubuntu-latest
    needs: parse-version
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Remove LADXR gfx
        run: rm -rf LADXR/gfx
      - name: Create executable
        uses: kbranch/pyinstaller-action@main
        with:
          python_ver: '3.12'
          spec: 'magpie-autotracker.spec'
          requirements: 'autotracking/requirements.txt'
      - run: mv dist/magpie-autotracker dist/magpie-autotracker-linux
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} dist/magpie-autotracker-linux', github.ref_name) }}

  build-autotracker-windows:
    runs-on: windows-latest
    needs: parse-version
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Remove LADXR gfx
        run: rm -r -fo LADXR/gfx
      - name: Create executable
        uses: kbranch/pyinstaller-action@main
        with:
          python_ver: '3.12'
          spec: 'magpie-autotracker.spec'
          requirements: 'autotracking/requirements.txt'
      - run: mv dist/magpie-autotracker dist\magpie-autotracker-linux
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} dist/magpie-autotracker-windows', github.ref_name) }}

  build-autotracker-macos:
    runs-on: macos-latest
    needs: parse-version
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Remove LADXR gfx
        run: rm -rf LADXR/gfx
      - name: Create executable
        uses: kbranch/pyinstaller-action@main
        with:
          python_ver: '3.12'
          spec: 'magpie-autotracker.spec'
          requirements: 'autotracking/requirements.txt'
      - run: mv dist/magpie-autotracker dist/magpie-autotracker-linux
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} dist/magpie-autotracker-macos', github.ref_name) }}
