name: Build offline version

on: workflow_dispatch

jobs:
  prep-magpie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build Vue
        run: npm install && npm run build
      - name: Remove cruft
        run: rm -rf LADXR/gfx node_modules
      - name: Upload Magpie
        uses: actions/upload-artifact@v4
        with:
          name: magpie
          path: '.'
  build-offline-linux:
    needs: prep-magpie
    runs-on: ubuntu-latest
    steps:
      - name: Download Magpie
        uses: actions/download-artifact@v4
        with:
          name: magpie
          path: '.'
      - run: pwd
      - run: chmod -R 755 vue-dist
      - run: ls -Rl vue-dist
      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'magpie-data.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'magpie-offline-linux'
  build-offline-windows:
    needs: prep-magpie
    runs-on: windows-latest
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Remove LADXR gfx
        run: rm -r -fo LADXR/gfx
      - name: Build Vue
        run: npm install; npm run build
      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'magpie-data.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'magpie-offline-windows'
  build-offline-macos:
    needs: prep-magpie
    runs-on: macos-latest
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Remove LADXR gfx
        run: rm -rf LADXR/gfx
      - name: Build Vue
        run: npm install && npm run build
      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'magpie-data.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'magpie-offline-macos'
